parameters:  
  location: 'westeurope'

steps:
- download: current
  artifact: app
- download: current
  artifact: arm
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: 'templates/deploy.ps1'
    arguments: '-location ${{ parameters.location }}'
  
- task: AzureFunctionApp@1
  displayName: Deploy Function App
  inputs:
    appName: $name-$stage-${{ parameters.location }}
    resourceGroupName: $name-$stage-$location
    azureSubscription: Visual Studio Enterprise – MPN
    appType: functionApp
    package: app.zip