# Build Number
name: $(Date:yyyyMMdd)$(Rev:.r)
# -------------------------------------------------------------------------------

trigger:
- feature/*
- hotfix/*
- refs/tags/*

stages:      
  - stage: build
    displayName: Build    
    jobs:    
      - job:    
        displayName: 'Build Application'  
        steps:
          - script: dotnet restore .            
          - script: dotnet build .            
          - script: dotnet test .
          - script: dotnet publish .
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)'
              artifact: 'build'              
          
  - stage: dev
    displayName: Development
    dependsOn: build
    jobs:
    - deployment: Development      
      environment: DEV
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - script: echo "Deploy"
  - stage: integrationtests
    displayName: Integration Tests
    dependsOn: dev
    jobs:
    - deployment: Testing      
      environment: TEST
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - script: echo "Deploy"
  - stage: componenttests
    displayName: Component Tests
    dependsOn: dev
    jobs:
    - deployment: Testing      
      environment: TEST
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - script: echo "Deploy"
  - stage: endtoendtests
    displayName: End-To-End Tests
    dependsOn: dev
    jobs:
    - deployment: Testing      
      environment: TEST
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - script: echo "Deploy"
  - stage: uat
    displayName: UAT
    dependsOn: 
    - componenttests
    - integrationtests
    - endtoendtests
    jobs:
    - deployment: Testing      
      environment: TEST
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - script: echo "Deploy"
  - stage: canary
    displayName: Production Canary
    dependsOn: uat
    jobs:
    - deployment: canary      
      environment: PROD
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - script: echo "Deploy"
  - stage: ea
    displayName: Production EarlyAdopters
    dependsOn: canary
    jobs:
    - deployment: ea      
      environment: PROD
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - script: echo "Deploy"
  - stage: prod
    displayName: Production Live
    dependsOn: ea
    jobs:
    - deployment: prod      
      environment: PROD
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - script: echo "Deploy"